### ISSUE TITLE
learn.py returning 401 HTTP response

### ISSUE THREAD

**Issue by ConorMatthews** [MrPowerScripts/reddit-learning-chat-bot#1]
Does anyone know how I could fix this?

**Comment by MrPowerScripts** [comment]
Did you follow all of the instructions on the readme? creating the app on reddit and adding your own keys to settings.py?

**Comment by ConorMatthews** [comment]
Yes, I have checked that they are all correct.
When i installed 'requirements.txt' using pip, I did say that it couldn't find the 'version that satisfies the requirement: pkg-resources==0.0.0' library. I deleted this line and ran pip again where it successfully installed all of the rest if this is an issue.

**Comment by ConorMatthews** [comment]
Fixed

**Comment by MrPowerScripts** [comment]
Do you mind sharing what the problem was @ConorMatthews ?

**Comment by ConorMatthews** [comment]
Sure, when I was copying and pasting in my keys it didn't actually copy it
properly as I was running it on my raspberry pi which led to the original
key being present. The 401 error mean access is denied, hence the wrong
keys.

**Comment by MrPowerScripts** [comment]
Cool. Thanks for the update!
