### ISSUE TITLE
Brain Python Library Code

### ISSUE THREAD

**Issue by morganfreemansvoice** [MrPowerScripts/reddit-learning-chat-bot#4]
May I please ask for a rundown of how the Brain python library code, responsible for the database and choosing which tokens/learned-words the bot will be using for the reply, is written because I would like to attempt customizing it to make it more efficient.

**Comment by Travis-Owens** [comment]
https://github.com/pteichman/cobe/wiki I think you may want to start here.

**Comment by MrPowerScripts** [comment]
Hello @morganfreemansvoice - Travis is right that's the best place to start. If you have any specific questions feel free to reach out but that is probably the best place to start.
